import os
import shutil
import subprocess
import sys
from typing import List, Dict
from app.core.config import settings
from .utils import clean_build_dirs, merge_requirements, get_feature_metadata
from .generators import CodeGenerator

class BuilderService:
    def __init__(self, package_name: str = settings.PACKAGE_NAME):
        self.package_name = package_name
        self.pkg_dir = settings.BUILD_DIR / self.package_name

    def _prepare_structure(self):
        """Internal method to setup folders."""
        clean_build_dirs()
        self.pkg_dir.mkdir(parents=True, exist_ok=True)
        
        # Create Root README
        with open(settings.BUILD_DIR / "README.md", "w", encoding="utf-8") as f:
            f.write(f"# {self.package_name}\n\nGenerated by AI Platform.")

    def _copy_sources(self, features: List[str]) -> List[Dict]:
        """
        Copies sources and returns a list of metadata dicts for the selected features.
        """
        init_lines = []
        loaded_meta = [] 

        for feature_dir in features:
            src_file = settings.REPO_PATH / feature_dir / "source.py"
            dest_file = self.pkg_dir / f"{feature_dir}.py"
            
            # 1. Load Metadata (Dynamic!)
            meta = get_feature_metadata(feature_dir)
            loaded_meta.append(meta)
            
            # 2. Copy File
            if src_file.exists():
                shutil.copy(src_file, dest_file)
                # Use class_name directly from your JSON
                class_name = meta.get("class_name", "UnknownClass")
                init_lines.append(f"from .{feature_dir} import {class_name}")
            else:
                print(f"⚠️ Warning: Source not found for {feature_dir}")

        # Write __init__.py
        with open(self.pkg_dir / "__init__.py", "w", encoding="utf-8") as f:
            f.write("\n".join(init_lines))
        return loaded_meta
    

    def build_wheel(self, features: List[str]) -> str:
        """Orchestrates the Wheel build process."""
        print(f"🏗️  Starting Wheel Build for: {features}")
        
        self._prepare_structure()
        self._copy_sources(features)
        
        # Handle Requirements & Setup.py
        reqs = merge_requirements(features)
        setup_content = CodeGenerator.generate_setup_py(self.package_name, reqs)
        
        with open(settings.BUILD_DIR / "setup.py", "w", encoding="utf-8") as f:
            f.write(setup_content)

        # Build Command
        print("🔨 Building Artifacts...")
        subprocess.run(
            [sys.executable, "-m", "build", "--wheel", "--outdir", str(settings.OUTPUT_DIR)],
            cwd=str(settings.BUILD_DIR),
            check=True
        )
        
        # Return path to generated file
        wheels = list(settings.OUTPUT_DIR.glob("*.whl"))
        if not wheels:
            raise RuntimeError("Build failed: No wheel file generated")
        return str(wheels[0])

    def build_standalone_zip(self, features: List[str]) -> str:
        """Orchestrates the ZIP App build process."""
        print(f"📦 Starting ZIP Build for: {features}")
        
        # Reuse preparation logic
        self._prepare_structure()
        self._copy_sources(features)
        
        # Generate Main.py runner
        reqs = merge_requirements(features)
        setup_content = CodeGenerator.generate_setup_py(self.package_name, reqs)
        
        with open(settings.BUILD_DIR / "setup.py", "w") as f: f.write(setup_content)
        
        main_content = CodeGenerator.generate_main_py(features, self.package_name)
        with open(settings.BUILD_DIR / "main.py", "w", encoding="utf-8") as f:
            f.write(main_content)
            
        with open(settings.BUILD_DIR / "run.sh", "w", encoding="utf-8") as f:
            f.write("#!/bin/bash\npip install .\npython main.py $1")

        # Zip it
        zip_name = "ai_application"
        shutil.make_archive(
            str(settings.OUTPUT_DIR / zip_name), 
            'zip', 
            str(settings.BUILD_DIR)
        )
        return str(settings.OUTPUT_DIR / f"{zip_name}.zip")